apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: "chuashihong"
        - name: MINIO_ROOT_PASSWORD
          value: "chuashihong"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: minio-data
          mountPath: /data
      # initContainers:
      # - name: create-bucket
      #   image: minio/mc:latest
      #   command: ["/bin/sh", "-c"]
      #   args:
      #   - |
      #     until (mc alias set myminio http://minio:9000 minioadmin minioadmin123); do
      #       echo "Waiting for MinIO to be ready...";
      #       sleep 5;
      #     done &&
      #     mc mb myminio/mybucket
      #   env:
      #   - name: MINIO_ROOT_USER
      #     value: "minioadmin"
      #   - name: MINIO_ROOT_PASSWORD
      #     value: "minioadmin"
      volumes:
      - name: minio-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: web-ui
      port: 44079
      targetPort: 44079
  selector:
    app: minio
