apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-3
  template:
    metadata:
      labels:
        app: db-3
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.14
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "chuashihong3"
---
apiVersion: v1
kind: Service
metadata:
  name: db-3-service
spec:
  selector:
    app: db-3
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
