apiVersion: v1
kind: Service
metadata:
  name: mysql-backup-log-data-service
spec:
  selector:
    app: mysql-backup-log-data
  ports:
    - protocol: TCP
      port: 3309         # Expose MySQL on this port externally (local machine)
      targetPort: 3306   # Target the MySQL container's internal port 3306
      nodePort: 30003    # NodePort will map traffic from external clients to MySQL
  type: NodePort
