apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # initContainers:
      # - name: init-mysql
      #   image: mysql:5.7
      #   command: ['sh', '-c', 'echo "CREATE DATABASE IF NOT EXISTS mydb;"']
      #   env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     value: "password123"
      initContainers:
      - name: init-mysql-binlog
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/log/mysql && chown -R 999:999 /var/log/mysql']
        volumeMounts:
        - name: mysql-binlog
          mountPath: /var/log/mysql
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306  # MySQL container port is 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123"
        volumeMounts:
        - name: mysql-config-volume
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
        - name: mysql-binlog
          mountPath: /var/log/mysql
      volumes:
      - name: mysql-config-volume
        configMap:
          name: mysql-config # Reference to the ConfigMap containing my.cnf
      - name: mysql-binlog
        emptyDir: {}