apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log_bin=/var/log/mysql/mysql-bin.log
    binlog_format=row
    expire_logs_days=10
    max_binlog_size=100M
